services:
  web:
    image: morbidus-mysql
    build: .
    restart: unless-stopped
    ports:
      - "80:5000"
    environment:
      - DATABASE_TYPE=MYSQL
      - DB_HOST=bd-mysql
      - DB_USER=morbidus
      - DB_PASS=marvel
      - DB_SCHEMA=morbidus
    depends_on:
      - bd-mysql
  
  bd-mysql:
    image: mysql:8.0-debian
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cige123456
      - MYSQL_DATABASE=morbidus
      - MYSQL_USER=morbidus
      - MYSQL_PASSWORD=marvel
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d