CREATE OR REPLACE PROCEDURE setup_database AS
BEGIN
   -- Apagar a tabela 'usuarios' se ela existir
   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE usuarios';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE != -942 THEN
            RAISE;
         END IF;
   END;

   -- Criar tabela de usuários
   EXECUTE IMMEDIATE '
      CREATE TABLE usuarios (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         username VARCHAR2(255) NOT NULL UNIQUE,
         password VARCHAR2(255) NOT NULL
      )';

   -- Inserir alguns usuários de exemplo com senhas hashadas em MD5
   EXECUTE IMMEDIATE 'INSERT INTO usuarios (username, password) VALUES (''joao'',  ''86232fc52644bdd06cdf42c3521627f1'')';
   EXECUTE IMMEDIATE 'INSERT INTO usuarios (username, password) VALUES (''maria'', ''e10adc3949ba59abbe56e057f20f883e'')';
   EXECUTE IMMEDIATE 'INSERT INTO usuarios (username, password) VALUES (''pedro'', ''3fb00fb776351db4f46be3b69a679756'')';
   EXECUTE IMMEDIATE 'INSERT INTO usuarios (username, password) VALUES (''admin'', ''86232fc52644bdd06cdf42c3521627f1'')';

   -- Apagar a tabela 'flag' se ela existir
   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE flag';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE != -942 THEN
            RAISE;
         END IF;
   END;

   -- Criar tabela de flags
   EXECUTE IMMEDIATE '
      CREATE TABLE flag (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         valor VARCHAR2(255) NOT NULL UNIQUE
      )';

   -- Inserir valor de exemplo na tabela flag
   EXECUTE IMMEDIATE 'INSERT INTO flag (valor) VALUES (''SACI{3413134123413}'')';

END setup_database;
/

BEGIN
   setup_database;
END;
/
